image:
  repository: docker.io/cynthiatoussi/pkarenov
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1"
imagePullSecrets:
  - name: pkarenov-staging-helm-chart
dockerconfigjson: {"auths":{"https://index.docker.io/v1/":{"auth":"Y3ludGhpYXRvdXNzaTpkY2tyX3BhdF9PLUpGM1BiVk0yUkN2ekNDb0hOb1BnUEpQc3M="}}}
ingress:
  enabled: true
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: staging.pkarenov.fr
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
